"""Add auth_id to User model

Revision ID: 79de0b981dd8
Revises: 59bb2488a76b
Create Date: 2024-10-16 17:06:45.820859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79de0b981dd8"
down_revision: Union[str, None] = "59bb2488a76b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("auth_id", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "auth_id")
    # ### end Alembic commands ###
