# Quality IDs
class QualityId:
    SAME_AGE = 1
    SAME_GENDER_IDENTITY = 2
    SAME_ETHNIC_OR_CULTURAL_GROUP = 3
    SAME_MARITAL_STATUS = 4
    SAME_PARENTAL_STATUS = 5
    SAME_DIAGNOSIS = 6


# Treatment IDs
class TreatmentId:
    UNKNOWN = 1
    WATCH_AND_WAIT = 2
    CHEMOTHERAPY = 3
    IMMUNOTHERAPY = 4
    ORAL_CHEMOTHERAPY = 5
    RADIATION = 6
    MAINTENANCE_CHEMOTHERAPY = 7
    PALLIATIVE_CARE = 8
    TRANSFUSIONS = 9
    AUTOLOGOUS_STEM_CELL_TRANSPLANT = 10
    ALLOGENEIC_STEM_CELL_TRANSPLANT = 11
    HAPLO_STEM_CELL_TRANSPLANT = 12
    CAR_T = 13
    BTK_INHIBITORS = 14


# Experience IDs
class ExperienceId:
    BRAIN_FOG = 1
    COMMUNICATION_CHALLENGES = 2
    COMPASSION_FATIGUE = 3
    FEELING_OVERWHELMED = 4
    FATIGUE = 5
    FERTILITY_ISSUES = 6
    GRAFT_VS_HOST = 7
    RETURNING_TO_WORK = 8
    SPEAKING_TO_FAMILY = 9
    RELAPSE = 10
    ANXIETY_DEPRESSION = 11
    PTSD = 12
