"""Add tasks table with type, priority, status enums

Revision ID: 0fb019b7af03
Revises: b56e0bf600a2
Create Date: 2025-10-02 21:01:02.761026

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fb019b7af03'
down_revision: Union[str, None] = 'b56e0bf600a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('intake_form_review', 'volunteer_app_review', 'profile_update', 'matching', name='task_type_enum'), nullable=False),
    sa.Column('priority', sa.Enum('no_status', 'low', 'medium', 'high', name='task_priority_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_progress', 'completed', name='task_status_enum'), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
