"""Add pending_volunteer_request field to User model

Revision ID: 14fdeccc883f
Revises: d87b1000d48b
Create Date: 2025-10-19 23:29:15.111257

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "14fdeccc883f"
down_revision: Union[str, None] = "d87b1000d48b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("pending_volunteer_request", sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "pending_volunteer_request")
    # ### end Alembic commands ###
