"""add_timezone_column_to_user_data

Revision ID: 2ccee7a88d08
Revises: 9f1a6d727929
Create Date: 2025-10-30 19:02:10.801071

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ccee7a88d08'
down_revision: Union[str, None] = '9f1a6d727929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('timezone', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'timezone')
    # ### end Alembic commands ###
