"""create schedules and timeblocks

Revision ID: 2fb1a0f3d14e
Revises: c9bc2b4d1036
Create Date: 2024-11-18 19:25:09.390236

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '2fb1a0f3d14e'
down_revision: Union[str, None] = 'c9bc2b4d1036'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
