"""add approved to users

Revision ID: 8bfb115acac1
Revises: c9bc2b4d1036
Create Date: 2025-06-04 16:50:38.609239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bfb115acac1"
down_revision: Union[str, None] = "c9bc2b4d1036"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("approved", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "approved")
    # ### end Alembic commands ###
