"""add rejected enum value to User model

Revision ID: 8d2cd99b9eb8
Revises: b56e0bf600a2
Create Date: 2025-10-30 19:50:23.495788

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d2cd99b9eb8"
down_revision: Union[str, None] = "b56e0bf600a2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'rejected' AND enumtypid = 'form_status_enum'::regtype) THEN
                ALTER TYPE form_status_enum ADD VALUE 'rejected';
            END IF;
        END $$;
    """)
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
