"""add scope column to experience table

Revision ID: 95467f4c5c80
Revises: 905b6788b114
Create Date: 2025-09-22 19:41:17.291555

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "95467f4c5c80"
down_revision: Union[str, None] = "905b6788b114"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    scope_enum = postgresql.ENUM("patient", "caregiver", "both", "none", name="scope")
    scope_enum.create(op.get_bind(), checkfirst=True)

    op.add_column(
        "experiences",
        sa.Column(
            "scope",
            scope_enum,
            nullable=False,
            server_default=sa.text("'none'::scope"),  # temporary default for NOT NULL
        ),
    )

    op.alter_column("experiences", "scope", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("experiences", "scope")
    # ### end Alembic commands ###
