"""remove other_treatment and other_experience columns from UserData table

Revision ID: a59aeb0bd691
Revises: 95467f4c5c80
Create Date: 2025-09-25 20:22:55.535261

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a59aeb0bd691'
down_revision: Union[str, None] = '95467f4c5c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'other_experience')
    op.drop_column('user_data', 'loved_one_other_experience')
    op.drop_column('user_data', 'other_treatment')
    op.drop_column('user_data', 'loved_one_other_treatment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('loved_one_other_treatment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_data', sa.Column('other_treatment', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_data', sa.Column('loved_one_other_experience', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('user_data', sa.Column('other_experience', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
