"""add soft deletion to matches table

Revision ID: d87b1000d48b
Revises: e3f0a5b4b7c4
Create Date: 2025-10-15 00:01:11.343457

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d87b1000d48b"
down_revision: Union[str, None] = "e3f0a5b4b7c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("matches", sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column("matches", "deleted_at")
    # ### end Alembic commands ###
