name: Lint codebase

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Filter changed files
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            frontend:
              - "frontend/**"
            backend:
              - "backend/**"
      
      - name: Set up Node.js
        if: steps.changes.outputs.frontend == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: "20.11.1"
          cache: "npm"
          cache-dependency-path: |
            frontend/package-lock.json

      - name: Install Node.js dependencies
        if: steps.changes.outputs.frontend == 'true'
        run: npm ci --prefix ./frontend

      - name: Lint frontend
        if: steps.changes.outputs.frontend == 'true'
        working-directory: ./frontend
        run: npx prettier . --check
      
      - name: Lint Python backend
        if: steps.changes.outputs.backend == 'true'
        working-directory: ./backend
        run: pip install ruff && ruff check . && ruff format --check .
